inherit_mode:
  merge:
    - Exclude # see: https://stackoverflow.com/a/70818366/473923
    - AllowedNames
require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  ExtraDetails: true
  NewCops: enable
  Exclude:
    - ".builders/**/*"
    - "spec/samples/**/*"

Metrics/BlockLength:
  Exclude:
    - "**/spec/**/*"
    - "*.gemspec"
    - "bin/gpt_context.rb"
  AllowedMethods:
    - configure
    - context
    - define
    - describe
    - draw
    - factory
    - feature
    - guard
    - included
    - it
    - let
    - let!
    - scenario
    - setup
    - shared_context
    - shared_examples
    - shared_examples_for
    - transaction

RSpec/ExampleLength:
  Max: 25

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "**/spec/**/*"
    - "bin/*.rb"

Layout/LineLength:
  Max: 200
  # Ignores annotate output
  # AllowedPatterns: ['\A# \*\*'] # this is renamed to AllowedPatterns and I need to come up with a template for this
  IgnoreCopDirectives: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Style/BlockComments:
  Enabled: false
  Include:
    - "**/spec/*"

# My Preferences - Start
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Exclude:
    - "**/spec/**/*"
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/VariableNumber:
  Exclude:
    - "**/spec/**/*"
Naming/MethodParameterName:
  AllowedNames:
    - as
Style/EmptyMethod:    
  Exclude:
    - "**/spec/**/*"
Metrics/ParameterLists:
  Exclude:
    - "**/spec/**/*"
    - "**/models/**/*"
Layout/EmptyLineBetweenDefs:
  Exclude:
    - "**/spec/**/*"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "**/spec/**/*"

Style/AccessorGrouping:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: false
# My Preferences - End

# RSpec Cops
RSpec/FilePath:
  Exclude:
    - "**/spec/**/*"

RSpec/NamedSubject:
  Exclude:
    - "**/spec/**/*"

RSpec/MultipleExpectations:
  Max: 8

RSpec/NestedGroups:
  Max: 8

RSpec/DescribeClass:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

Metrics/AbcSize:
  Max: 25
  Exclude:
    - "bin/*"
Metrics/CyclomaticComplexity:
  Exclude:
    - "**/models/**/*"
    - "lib/appydave/tools/bank_reconciliation/clean/mapper.rb"
Metrics/PerceivedComplexity:
  Exclude:
    - "**/models/**/*"
RSpec/MultipleMemoizedHelpers:
  Enabled: false
